version: "3.4"

services:
  seafoodapi:
    image: lephuminh/seafoodapi
    # build:
    #   context: .
    #   dockerfile: SeafoodApi/Dockerfile
  db:
    image: lephuminh/seadb
  nginx:
    image: nginx:1.23.3
     ports:
      - 80:80
    volumes:
      - ../SeafoodWeb/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
